apiVersion: v1
kind: Service
metadata:
  name: application-pgpool-service
  labels:
    name: database-balancer
    node: pgpool
    system: application
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    name: database-balancer
    node: pgpool
    system: application