apiVersion: v1
kind: Service
metadata:
  name: application-db-node1-service
  labels:
    name: database
    node: node1
    system: application
spec:
  ports:
    - port: 5432
  selector:
    name: database
    node: node1
    system: application
